'use client';
import React from 'react';

const CollectionReportSheet = ({ paymentsLog, totalCollected, filterType, apiDates }) => {
  
  // 🔢 SL নাম্বারকে ৩ ডিজিটে রূপান্তর করার হেল্পার ফাংশন
  const formatSlNumber = (sl) => {
    if (!sl && sl !== 0) return 'N/A';
    return String(sl).padStart(3, '0');
  };

  return (
    <div id="printable-area" className="bg-white rounded-xl shadow-sm p-4 md:p-8 border border-gray-200 max-w-5xl mx-auto mt-6 relative min-h-[500px] flex flex-col justify-between">
      
      {/* 🔝 মূল কন্টেন্ট এরিয়া (টেবিল) */}
      <div>
        {/* 🖨️ প্রিন্ট হেড */}
        <div className="text-center mb-8 hidden print:block">
          <h1 className="text-2xl font-normal text-gray-900 uppercase tracking-wide">ICC Communication</h1>
          <p className="text-base font-normal text-gray-700 mt-1">Daily Collection Report</p>
          <div className="text-right text-sm font-normal text-gray-800 mt-4">
            Date: {new Date().toLocaleDateString('en-GB')}
          </div>
        </div>

        {/* 📝 মূল খাতার ডাটা টেবিল (ওয়েব ভিউতেও বর্ডার চিকন করা হয়েছে) */}
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse border border-gray-400 text-base table-fixed">
            <thead>
              <tr className="bg-gray-50 text-black font-normal border-b border-gray-400 text-sm uppercase">
                <th className="py-2.5 px-3 border border-gray-400 text-center font-normal w-[12%]">SL</th>
                <th className="py-2.5 px-3 border border-gray-400 text-center font-normal w-[18%]">From</th>
                <th className="py-2.5 px-3 border border-gray-400 font-normal w-[40%]">Name</th>
                <th className="py-2.5 px-3 border border-gray-400 font-normal w-[15%]">Due Bill.</th>
                <th className="py-2.5 px-3 border border-gray-400 text-right font-normal w-[15%]">Running BILL</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-400 text-black font-normal">
              {paymentsLog.length === 0 ? (
                <tr>
                  <td colSpan="5" className="text-center py-12 text-gray-400 italic text-base font-normal">
                    No data found for this selected date range.
                  </td>
                </tr>
              ) : (
                <>
                  {paymentsLog.map((payment) => (
                    <tr key={payment?._id} className="hover:bg-gray-50/50">
                      <td className="py-2.5 px-3 border border-gray-400 text-center font-mono text-sm font-normal text-black whitespace-nowrap">
                        {formatSlNumber(payment?.sl)}
                      </td>
                      <td className="py-2.5 px-3 border border-gray-400 text-center font-mono text-sm text-black font-normal break-all">
                        {payment?.receiptNo || 'N/A'}
                      </td>
                      <td className="py-2.5 px-3 border border-gray-400 text-base font-normal text-black break-words">
                        {payment?.client_name}
                      </td>
                      <td className="py-2.5 px-3 border border-gray-400"></td>
                      <td className="py-2.5 px-3 border border-gray-400 text-right text-base font-normal text-black whitespace-nowrap">
                        {payment?.amount}/=
                      </td>
                    </tr>
                  ))}
                  
                  {/* মোট যোগফল রো */}
                  <tr className="bg-gray-50/50 text-black border-t border-gray-400">
                    <td colSpan="3" className="py-3 px-3 border border-gray-400 text-right"></td>
                    <td className="py-3 px-3 border border-gray-400 text-center text-base font-medium text-gray-700">Total:</td>
                    <td className="py-3 px-3 border border-gray-400 text-right text-base font-normal text-black whitespace-nowrap">
                      {totalCollected}/=
                    </td>
                  </tr>
                </>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ⏬ 🖨️ একদম নিচে মার্জিনের কোণায় জেনারেটেড টেক্সট */}
      <div className="mt-12 text-right text-xs italic text-gray-500 font-mono tracking-wide print:fixed print:bottom-2 print:right-2 print:text-black">
        Generated by: Mahialam Rahat
      </div>

      {/* 🖨️ প্রিন্ট কাস্টম সিএসএস (বর্ডার গ্লিচ ফিক্সড) */}
      <style jsx global>{`
        @media print {
          @page {
            margin: 10mm 8mm 12mm 8mm; 
          }
          .no-print, .btn, select, input, footer, nav {
            display: none !important;
          }
          body { 
            background-color: white !important; 
            padding: 0 !important;
            margin: 0 !important;
            font-weight: normal !important;
            color: #000000 !important;
          }
          #printable-area { 
            box-shadow: none !important; 
            border: none !important; 
            max-w: 100% !important; 
            width: 100% !important; 
            padding: 0 !important; 
            margin: 0 !important;
            min-h: 100vh !important;
          }
          /* ⚡ বর্ডার অতিরিক্ত ডার্কনেস ফিক্স: কালো রং বদলে হালকা গ্রে (#999) এবং হেয়ারলাইন থিকনেস করা হলো */
          table { 
            border: 0.5px solid #999999 !important; 
            table-layout: fixed !important; 
            width: 100% !important;
            border-collapse: collapse !important;
          }
          th, td { 
            border: 0.5px solid #999999 !important; 
            color: #000000 !important; 
            padding: 8px 6px !important;
            font-weight: normal !important;
          }
        }
      `}</style>
    </div>
  );
};

export default CollectionReportSheet;